export const SET_CONTACTS = 'SET_CONTACTS';
export const CONTACT_ALERT = 'CONTACT_ALERT';
export const CONTACT_LOADING = 'CONTACT_LOADING';

export const SET_TESTIMONIAL = 'SET_TESTIMONIAL';
export const DELETE_TESTIMONIAL = 'DELETE_TESTIMONIAL';
export const SETUPDATE_TESTIMONIAL = 'SETUPDATE_TESTIMONIAL';
export const TESTIMONIAL_LOADING = 'TESTIMONIAL_LOADING';
export const TESTIMONIAL_ALERT = 'TESTIMONIAL_ALERT';
export const ADDTESTIMONIAL_LOADING = 'ADDTESTIMONIAL_LOADING';
export const DELETE_TESTIMONIALLOADING = 'DELETE_TESTIMONIALLOADING';

export const SET_EOM = 'SET_EOM';
export const SET_EOMADMIN = 'SET_EOMADMIN';
export const EOM_ALERT = 'EOM_ALERT';
export const DELETE_EOM = 'DELETE_EOM';
export const SETUPDATE_EOM = 'SETUPDATE_EOM';
export const EOM_LOADING = 'EOM_LOADING';
export const ADDEOM_LOADING = 'ADDEOM_LOADING';
export const DELETE_EOMLOADING = 'DELETE_EOMLOADING';

export const SETCLIENT_CAROUSEL = 'CLIENT_CAROUSEL';
export const SETUPDATECLIENT_CAROUSEL = 'SETUPDATECLIENT_CAROUSEL';
export const CLIENT_CAROUSELALERT = 'CLIENT_CAROUSELALERT';
export const DELETECLIENT_CAROUSEL = 'DELETECLIENT_CAROUSEL';
export const CLIENTCAROUSEL_LOADING = 'CLIENTCAROUSEL_LOADING';
export const ADDCLIENT_LOADING = 'ADDCLIENT_LOADING';
export const DELETECLIENT_CAROUSELLOADING = 'DELETECLIENT_CAROUSELLOADING';

export const SET_TEAM = 'SET_TEAM';
export const DELETE_TEAM = 'DELETE_TEAM';
export const SETUPDATE_TEAM = 'SETUPDATE_TEAM';
export const TEAM_LOADING = 'TEAM_LOADING';
export const TEAM_ALERT = 'TEAM_ALERT';
export const ADDTEAM_LOADING = 'ADDTEAM_LOADING';
export const DELETE_TEAMLOADING = 'DELETE_TEAMLOADING';

export const SET_USERDETAILS = 'SET_USERDETAILS';
export const SET_JWT = 'SET_JWT';
export const IS_AUTH = 'IS_AUTH';

export const GET_USERS = 'GET_USERS';
export const GET_STUDENTS = 'GET_STUDENTS';
export const GET_INSTRUCTORS = 'GET_INSTRUCTORS';
export const GET_EMPLOYEE = 'GET_EMPLOYEE';

export const GET_CLASSES = 'GET_CLASSES';
export const ADD_CLASS = 'ADD_CLASS';
export const ENROLL_CLASS = 'ENROLL_CLASS';
export const DELETE_CLASS = 'DELETE_CLASS';
export const GET_CLASSESLOADING = 'GET_CLASSESLOADING';

export const GET_BASKET = 'GET_BASKET';
export const ADD_BASKET = 'ADD_BASKET';
export const ENROLL_BASKET = 'ENROLL_BASKET';
export const DELETE_BASKET = 'DELETE_BASKET';
export const UPDATEBASKET_STATUS = 'UPDATEBASKET_STATUS';

export const GETALL_COURSES = 'GETALL_COURSES';
export const GETUSERS_COURSE = 'GETUSERS_COURSE';
export const COURSE_LOADING = 'COURSE_LOADING';
export const GET_PROGRESS = 'GET_PROGRESS';
export const SET_CURRENTCOURSE = 'SET_CURRENTCOURSE';
export const UPADTE_CURRENTMODULE = 'UPADTE_CURRENTMODULE';
export const UPADTE_CURRENTCHAPTER = 'UPADTE_CURRENTCHAPTER';
export const UPADTE_CURRENTSLIDE = 'UPADTE_CURRENTSLIDE';
export const UPADTE_CURRENTTIMESTAMP = 'UPADTE_CURRENTTIMESTAMP';
export const UPADTE_COMPLETEDMODULE = 'UPADTE_COMPLETEDMODULE';
export const UPADTE_COMPLETEDCHAPTER = 'UPADTE_COMPLETEDCHAPTER';

export const SET_REQUIREMENT = 'SET_REQUIREMENT';
export const DELETE_REQUIREMENT = 'DELETE_REQUIREMENT';
export const SETUPDATE_REQUIREMENT = 'SETUPDATE_REQUIREMENT';
export const REQUIREMENT_LOADING = 'REQUIREMENT_LOADING';
export const REQUIREMENT_ALERT = 'REQUIREMENT_ALERT';
export const ADDREQUIREMENT_LOADING = 'ADDREQUIREMENT_LOADING';
export const DELETE_REQUIREMENTLOADING = 'DELETE_REQUIREMENTLOADING';

export const NOT_LOADING = 'NOT_LOADING';
export const MESSAGE_LOADING = 'MESSAGE_LOADING';
export const GET_NOTIFICATION = 'GET_NOTIFICATION';
export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const GET_MESSAGE = 'GET_MESSAGE';
